/*
 hello 007
 */
package com.example.mobile_data_achrf;


public class ForensicsException extends Exception {
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -153702376106197071L;
	
	public ForensicsException(Exception ex) {
		super(ex);
	}
	
	public ForensicsException(String msg) {
		super(msg);
	}
	
	public ForensicsException(Exception ex, String msg) {
		super(msg, ex);
	}
}
